"""Generate strongly keyed, AOT-safe English resources and the host-language map."""
from pathlib import Path
import argparse
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[2]
RESOURCE = ROOT / 'src/CsvVisualEditor.Localization'

def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)

def products() -> dict[Path, str]:
    catalog = json.loads((RESOURCE / 'Catalogs/en.json').read_text(encoding='utf-8'))['messages']
    inventory = json.loads((RESOURCE / 'languages.json').read_text(encoding='utf-8'))['languages']
    policy = json.loads((RESOURCE / 'translations.json').read_text(encoding='utf-8'))
    keys = sorted(catalog)
    enum = '// <auto-generated />\nnamespace CsvVisualEditor.Localization;\n\npublic enum TextKey\n{\n'
    enum += ''.join('    ' + key.replace('.', '_') + ',\n' for key in keys) + '}\n'
    arrays = '// <auto-generated />\nnamespace CsvVisualEditor.Localization;\n\ninternal static class EnglishText\n{\n'
    for name, values in [('Keys',keys),('Values',[catalog[key]['text'] for key in keys]),
        ('SourceHashes',[hashlib.sha256(catalog[key]['text'].encode()).hexdigest() for key in keys])]:
        arrays += '    internal static readonly string[] ' + name + ' =\n    [\n'
        arrays += ''.join('        ' + quoted(value) + ',\n' for value in values) + '    ];\n'
    arrays += '}\n'
    lang = '// <auto-generated />\nnamespace CsvVisualEditor.Localization;\n\ninternal static class LanguageInventory\n{\n'
    lang += '    internal static readonly LanguageDefinition English = new("english.xml", "en", "English", false);\n'
    lang += '    internal static readonly IReadOnlyList<LanguageDefinition> All = Array.AsReadOnly(new LanguageDefinition[]\n    {\n'
    for entry in inventory:
        lang += '        new(' + ', '.join([quoted(entry['file']),quoted(entry['code']),quoted(entry['name']),str(entry['rtl']).lower()]) + '),\n'
    lang += '    });\n}\n'
    translated = policy['translatedCodes']
    available = {entry['code'] for entry in inventory}
    if policy.get('fallback') != 'en' or 'en' not in translated or len(translated) != len(set(translated)) or set(translated) - available:
        raise ValueError('Invalid translation policy')
    policy_cs = '// <auto-generated />\nnamespace CsvVisualEditor.Localization;\n\ninternal static class TranslationPolicy\n{\n'
    policy_cs += '    internal static readonly IReadOnlySet<string> SupportedCodes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)\n    {\n'
    policy_cs += ''.join('        ' + quoted(code) + ',\n' for code in translated) + '    };\n}\n'
    return {RESOURCE/'TextKey.g.cs':enum,RESOURCE/'EnglishText.g.cs':arrays,RESOURCE/'LanguageInventory.g.cs':lang,RESOURCE/'TranslationPolicy.g.cs':policy_cs}

if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    stale=[]
    for path,text in products().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8')!=text:stale.append(str(path.relative_to(ROOT)))
        else:path.write_text(text,encoding='utf-8',newline='\n')
    if stale:raise SystemExit('Generated resources are stale: '+', '.join(stale))
